records/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('transactions.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

transactions/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('bank_overview/', views.bank_overview, name='bank_overview'),
    path('mt_overview/', views.mt_overview, name='mt_overview'),
    path('bank_record/', views.bank_record, name='bank_record'),
    path('mt_record/', views.mt_record, name='mt_record'),
    path('users/', views.user_list, name='user_list'),
    path('users/delete/<int:user_id>/', views.delete_user, name='delete_user'),
    path('users/approve/<int:user_id>/', views.approve_staff, name='approve_staff'),
]

transactions/models.py
from django.db import models

# Create your models here.
# models.py

class BankTransaction(models.Model):
    BANK_CHOICES = [
        ('equity_bank', 'Equity Bank'),
        ('bk', 'BK'),
        ('ecobank', 'Ecobank'),
    ]
    bank_name = models.CharField(max_length=255, choices=BANK_CHOICES)
    transaction_type = models.CharField(max_length=10, choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')])
    client_name = models.CharField(max_length=255)
    client_id_passport = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField(auto_now_add=True)

    class Meta:
        unique_together = ('client_id_passport', 'amount', 'date')

class MoneyTransferTransaction(models.Model):
    COMPANY_CHOICES = [
        ('western_union', 'Western Union'),
        ('moneygram', 'MoneyGram'),
        ('mpesa', 'M-Pesa'),
        ('dubai', 'Dubai'),
    ]

    sender_name = models.CharField(max_length=255)
    sender_id_passport = models.CharField(max_length=255)
    transaction_type = models.CharField(max_length=10, choices=[('send', 'Send Money'), ('receive', 'Receive Money')])
    location = models.CharField(max_length=255)
    company = models.CharField(max_length=20, choices=COMPANY_CHOICES)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField(auto_now_add=True)

    class Meta:
        unique_together = ('sender_id_passport', 'amount', 'date')

transactions/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth import authenticate, login as auth_login, logout
from django.contrib import messages
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
from .decorators import *
from .models import *
from django.db.models import Sum
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

def login(request):  
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect('bank_overview')  # Redirect to the desired page after successful login
        else:
            messages.error(request, 'Invalid username or password.')
            return redirect('login')
    return render(request, 'cre/login.html')


def logout_view(request):
    logout(request)
    return redirect('login') 

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        # role = request.POST['role']  # Get the selected role from the dropdown

        user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name, email=email, password=password)
        user.save()
        # Redirect to the desired page after successful signup (e.g., login page)
        return redirect('login')
       
    return render(request, 'cre/signup.html')


# def overview(request):
#   template = loader.get_template('ui/test2.html')
#   return HttpResponse(template.render())

# def bank_overview(request):
#     # Get filter parameters from GET request
#     bank_name = request.GET.get('bank_name')
#     transaction_type = request.GET.get('transaction_type')
#     start_date = request.GET.get('start_date')
#     end_date = request.GET.get('end_date')

#     # Get all transactions by default
#     transactions = BankTransaction.objects.all()

#     # Apply filters based on parameters
#     if bank_name:
#         transactions = transactions.filter(bank_name=bank_name)
#     if transaction_type:
#         transactions = transactions.filter(transaction_type=transaction_type)
#     if start_date:
#         transactions = transactions.filter(date__gte=start_date)
#     if end_date:
#         transactions = transactions.filter(date__lte=end_date)
    
#     total_amount = transactions.aggregate(Sum('amount'))['amount__sum']

#     template = 'ui/test2.html'
#     context = {'transactions': transactions, 'total_amount': total_amount}
#     return render(request, template, context)
@login_required
@group_required('Supervisor')
def bank_overview(request):
    bank_name = request.GET.get('bank_name')
    transaction_type = request.GET.get('transaction_type')
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')

    transactions = BankTransaction.objects.all()

    if bank_name:
        transactions = transactions.filter(bank_name=bank_name)
    if transaction_type:
        transactions = transactions.filter(transaction_type=transaction_type)
    if start_date:
        transactions = transactions.filter(date__gte=start_date)
    if end_date:
        transactions = transactions.filter(date__lte=end_date)

    # Pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(transactions, 10)  # Show 10 transactions per page

    try:
        transactions = paginator.page(page)
    except PageNotAnInteger:
        transactions = paginator.page(1)
    except EmptyPage:
        transactions = paginator.page(paginator.num_pages)

    total_amount = transactions.object_list.aggregate(Sum('amount'))['amount__sum']

    template = 'ui/test2.html'
    context = {'transactions': transactions, 'total_amount': total_amount}
    return render(request, template, context)

# def mt_overview(request):
#     # Get filter parameters from GET request
#     company = request.GET.get('company')
#     sender_name = request.GET.get('sender_name')
#     transaction_type = request.GET.get('transaction_type')
#     start_date = request.GET.get('start_date')
#     end_date = request.GET.get('end_date')

#     # Get all money transfer transactions by default
#     transactions = MoneyTransferTransaction.objects.all()

#     # Apply filters based on parameters
#     if company:
#         transactions = transactions.filter(company=company)
#     if sender_name:
#         transactions = transactions.filter(sender_name=sender_name)
#     if transaction_type:
#         transactions = transactions.filter(transaction_type=transaction_type)
#     if start_date:
#         transactions = transactions.filter(date__gte=start_date)
#     if end_date:
#         transactions = transactions.filter(date__lte=end_date)

#     total_amount = transactions.aggregate(Sum('amount'))['amount__sum']

#     template = 'ui/mt_overview.html'  # Adjust the template path accordingly
#     context = {'transactions': transactions, 'total_amount': total_amount}
#     return render(request, template, context)
@login_required
def mt_overview(request):
    # Get filter parameters from GET request
    company = request.GET.get('company')
    sender_name = request.GET.get('sender_name')
    transaction_type = request.GET.get('transaction_type')
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')

    # Get all money transfer transactions by default
    transactions = MoneyTransferTransaction.objects.all()

    # Apply filters based on parameters
    if company:
        transactions = transactions.filter(company=company)
    if sender_name:
        transactions = transactions.filter(sender_name=sender_name)
    if transaction_type:
        transactions = transactions.filter(transaction_type=transaction_type)
    if start_date:
        transactions = transactions.filter(date__gte=start_date)
    if end_date:
        transactions = transactions.filter(date__lte=end_date)

    # Pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(transactions, 10)  # Show 10 transactions per page

    try:
        transactions = paginator.page(page)
    except PageNotAnInteger:
        transactions = paginator.page(1)
    except EmptyPage:
        transactions = paginator.page(paginator.num_pages)

    total_amount = transactions.object_list.aggregate(Sum('amount'))['amount__sum']

    template = 'ui/mt_overview.html'  # Adjust the template path accordingly
    context = {'transactions': transactions, 'total_amount': total_amount}
    return render(request, template, context)

@login_required
def bank_record(request):
    if request.method == 'POST':
        # Retrieve data from the form
        bank_name = request.POST.get('bank_name')
        transaction_type = request.POST.get('transaction_type')
        client_name = request.POST.get('client_name')
        client_id_passport = request.POST.get('client_id_passport')
        amount = request.POST.get('amount')

        # Create a new BankTransaction instance and save it
        BankTransaction.objects.create(
            bank_name=bank_name,
            transaction_type=transaction_type,
            client_name=client_name,
            client_id_passport=client_id_passport,
            amount=amount
        )

        return redirect('bank_record')  # Redirect to the overview page or any other page

    template = 'ui/rec.html'
    return render(request, template)
@login_required
def mt_record(request):
    if request.method == 'POST':
        # Retrieve data from the form
        sender_name = request.POST.get('sender_name')
        sender_id_passport = request.POST.get('sender_id_passport')
        transaction_type = request.POST.get('transaction_type')
        location = request.POST.get('location')
        company = request.POST.get('company')
        amount = request.POST.get('amount')

        # Create a new MoneyTransferTransaction instance and save it
        MoneyTransferTransaction.objects.create(
            sender_name=sender_name,
            sender_id_passport=sender_id_passport,
            transaction_type=transaction_type,
            location=location,
            company=company,
            amount=amount
        )

        return redirect('mt_record')  # Redirect to the overview page for money transfer transactions

    template = 'ui/mt_rec.html'  
    return render(request, template)



def user_list(request):
    users = User.objects.all()
    return render(request, 'ui/user_list.html', {'users': users})

def delete_user(request, user_id):
    if request.method == 'POST':
        try:
            user = User.objects.get(id=user_id)
            user.delete()
            messages.success(request, f"User '{user.username}' has been deleted.")
        except User.DoesNotExist:
            messages.error(request, "User not found.")
    return redirect('user_list')

def approve_staff(request, user_id):
    if request.method == 'POST':
        try:
            user = User.objects.get(id=user_id)
            user.is_staff = True
            user.save()
            messages.success(request, f"Staff status for '{user.username}' has been approved.")
        except User.DoesNotExist:
            messages.error(request, "User not found.")
    return redirect('user_list')

transactions/templates/ui/mt_overview.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}
{% block content %}
   <style>
    .main-btn2 {
  display: inline-block;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  padding: 15px 15px;
  font-weight: 500;
  font-size: 14px;
  line-height: 4px;
  border-radius: 64px;
  cursor: pointer;
  z-index: 5;
  transition: all 0.4s ease-in-out;
  border: 1px solid transparent;
  overflow: hidden;
  margin: 5px
}
    .pagination-buttons-container {
  display: flex;
  justify-content: center;
  position: fixed;
  bottom: 20px; /* Adjust this value to set the desired distance from the bottom */
  left: 0;
  right: 0;
  z-index: 999; /* Ensure the buttons appear above other elements */
}
#map {
  height: 500px;
 }
.select-style-1 .select-position.select-sm::after {
    margin-top: 8px;
  }
   </style>
    <!-- ======== sidebar-nav end =========== -->

    <!-- ======== main-wrapper start =========== -->
    
      <!-- ========== header start ========== -->
      
      <!-- ========== header end ========== -->

      <!-- ========== section start ========== -->
      <section class="section">
        <div class="container-fluid">
          <!-- ========== title-wrapper start ========== -->
          <div class="title-wrapper pt-30">
            <div class="row align-items-center">
              <div class="col-md-6">
                <div class="title mb-30">
                  <h2>Overview Dashboard</h2>
                </div>
              </div>
              <!-- end col -->
              <div class="col-md-6">
                <div class="breadcrumb-wrapper mb-30">
                  <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item">
                        <a href="#0">Dashboard</a>
                      </li>
                      <li class="breadcrumb-item active" aria-current="page">
                        Overview
                      </li>
                    </ol>
                  </nav>
                </div>
              </div>
              <!-- end col -->
            </div>
            <!-- end row -->
          </div>
          <!-- ========== title-wrapper end ========== -->
          <div class="row">
            <div class="col-xl-3 col-lg-4 col-sm-6">
              <div class="icon-card mb-30">
                <div class="icon purple">
                  <i class="lni lni-cart-full"></i>
                </div>
                <div class="content">
                  <h6 class="mb-10">Total Products</h6>
                  <h3 class="text-bold mb-10" id="total-products"></h3>
                  
                </div>
              </div>
              <!-- End Icon Cart -->
            </div>
            <!-- End Col -->
            <div class="col-xl-3 col-lg-4 col-sm-6">
              <div class="icon-card mb-30">
                <div class="icon success">
                  <i class="lni lni-dollar"></i>
                </div>
                <div class="content">
                  <h6 class="mb-10">Total Income</h6>
                  <h3 class="text-bold mb-10" id="total-sales"></h3>
                  <p class="text-sm text-success" id="percentage-difference">
                   
                  </p>
                </div>
              </div>
              <!-- End Icon Cart -->
            </div>
            <!-- End Col -->
            <div class="col-xl-3 col-lg-4 col-sm-6">
              <div class="icon-card mb-30">
                <div class="icon primary">
                  <i class="lni lni-credit-cards"></i>
                </div>
                <div class="content">
                  <h6 class="mb-10">Total Target</h6>
                  <h3 class="text-bold mb-10" id="total-targets"></h3>
                </div>
              </div>
              <!-- End Icon Cart -->
            </div>
            <!-- End Col -->
            <div class="col-xl-3 col-lg-4 col-sm-6">
              <div class="icon-card mb-30">
                <div class="icon orange">
                  <i class="lni lni-user"></i>
                </div>
                <div class="content">
                  <h6 class="mb-10">Total Customers</h6>
                  <h3 class="text-bold mb-10" id="total-customers"></h3>
                  
                </div>
              </div>
              <!-- End Icon Cart -->
            </div>
            <!-- End Col -->
          </div>
          <!-- End Row -->

          <!-- FILTERS -->
          <form action="{% url 'mt_overview' %}" method="get">
            <div class="row" id="targetDiv">
              <div class="col-lg-12">
                <div class="card-style mb-30">
                  <!-- Use "d-flex" to create a flex container and "flex-wrap" to wrap the items to the next line if necessary. -->
                  <div class="d-flex flex-wrap align-items-center justify-content-between">
                    <!-- "mb-2" adds margin-bottom to create spacing between the filters. -->
                    <div class="select-style-1 mb-2">
                      <div class="select-position select-sm">
                        <label for="sales-month-filter">Month:</label>
                        <!-- The "light-bg" class is used for styling purposes. -->
                        <select id="sales-month-filter" class="light-bg">
                          <!-- Options for Sales Month -->
                          <option value="">All</option>
                          <option value="January">January</option>
                          <option value="February">February</option>
                          <option value="March">March</option>
                          <option value="April">April</option>
                          <option value="May">May</option>
                          <option value="June">June</option>
                          <option value="July">July</option>
                          <option value="August">August</option>
                          <option value="September">September</option>
                          <option value="October">October</option>
                          <option value="November">November</option>
                          <option value="December">December</option>
                        </select>
                      </div>
                    </div>
            
                    <!-- Repeat the same structure for other filters. -->
                    <div class="select-style-1 mb-2">
                      <div class="select-position select-sm">
                        <label for="company">Company:</label>
                        <select name="company" class="light-bg">
                          <!-- Options for Profile -->
                          <option value="">All</option>
                          <option value="western_union">Western Union</option>
                          <option value="moneygram">MoneyGram</option>
                          <option value="mpesa">M-Pesa</option>
                          <option value="dubai">Dubai</option>
                        </select>
                      </div>
                    </div>
            
                    <div class="select-style-1 mb-2">
                      <div class="select-position select-sm">
                        <label for="transaction_type">Transaction Type:</label>
                        <select name="transaction_type" class="light-bg">
                          <!-- Options for Profile -->
                          <option value="">All</option>
                          <option value="send">Send Money</option>
                          <option value="receive">Receive Money</option>
                        </select>
                      </div>
                    </div>
            
                    
                    
                    <div class="select-style-1 mb-2">
                      <div class="select-position select-sm">
                        <label for="start_date">Date:</label>
                        <select name="start_date" class="light-bg">
                          <!-- Options for Customer Category -->
                          <option value="">All</option>
                          <option value="Standard">From</option>
                          <option value="VIP">To</option>
                        </select>
                      </div>
                    </div>
                    <button type="submit" class="main-btn primary-btn btn-hover">Filter</button>
                  </div>
                </div>
              </div>
            </div>
          </form>

          <!--all sales-->
          <div class="row">
            <div class="col-lg-12">
           <div class="card-style mb-30">
             <div
               class="
                 title
                 d-flex
                 flex-wrap
                 align-items-center
                 justify-content-between
               "
             >
               <div class="left">
                 <h6 class="text-medium mb-30">Money Transfer Transactions</h6>
               </div>
               
             </div>
             <!-- End Title -->
             <div class="table-responsive">
               
               <table id="data-table" class="table top-selling-table">
                 <thead>
                   <tr>
                     <th><h6 class="text-sm text-medium">Company Name</h6></th>
                     <th class="min-width"><h6 class="text-sm text-medium">Transaction Type</h6></th>
                     <th class="min-width"><h6 class="text-sm text-medium">Client Name</h6></th>
                     <th class="min-width"><h6 class="text-sm text-medium">Amount</h6></th>
                     <th class="min-width"><h6 class="text-sm text-medium">Date </h6></th>
                   </tr>
                 </thead>
                 <tbody>
                   <!-- table rows will be dynamically added using JavaScript -->
                   {% for transaction in transactions %}
                   <tr>
                     <td class="min-width"><p><a href="#0">{{ transaction.get_company_display }}</a></p></td>
                     <td class="min-width"><p>{{ transaction.transaction_type }}</p></td>
                     <td class="min-width"><p>{{ transaction.sender_name }}</p></td>
                     <td class="min-width"><p>{{ transaction.amount|intcomma }}</p></td>
                     <td class="min-width"><p>{{ transaction.date }}</p></td>
                   </tr>
                   {% endfor %}
                   <!-- <tr>
                    <td class="min-width">
                      <p><a href="#0">Equity Bank</a></p>
                    </td>
                    <td class="min-width">
                      <p>Deposit</p>
                    </td>
                    <td class="min-width">
                      <p>John</p>
                    </td>
                    <td class="min-width">
                      <p>10000</p>
                    </td>
                    <td class="min-width">
                      <p>11-11-2019</p>
                    </td>
                  </tr> -->
                 </tbody>
               </table>
               <p>Total Amount: <span class="fw-bold">{{ total_amount|intcomma }}</span> </p>
               <!-- End Table -->
               <div class="pagination">
                <span class="step-links">
                    {% if transactions.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ transactions.previous_page_number }}">previous</a>
                    {% endif %}
            
                    <span class="current">
                        Page {{ transactions.number }} of {{ transactions.paginator.num_pages }}.
                    </span>
            
                    {% if transactions.has_next %}
                        <a href="?page={{ transactions.next_page_number }}">next</a>
                        <a href="?page={{ transactions.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
               <!-- <div id="pagination-buttons" class="pagination-buttons d-flex justify-content-center"></div> -->
             </div>
           </div>
         </div>
       </div>


       

          
      </section>
      <!-- ========== section end ========== -->

      
    </main>
    <!-- ======== main-wrapper end =========== -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
        // Hide the div initially (optional)
        $('#targetDiv').hide();
    
        // Add click event listener to the button
        $('#toggleButton').on('click', function() {
        // Toggle the visibility of the div
        $('#targetDiv').toggle();
        });
        });
    </script>
  

    
{% endblock content %}

transactions/templates/ui/mt_rec.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<main class="main-wrapper">

  <!-- ========== header end ========== -->

  <div class="form-container">
      <section class="table-components">
      <div class="col-lg-6">
        <div class="card-style settings-card-2 mb-30">
          {% include 'partials/alerts.html' %}
          <div class="title mb-30">
            <h6>Register</h6>
          </div>
          <form method="post" id="register-form" action="{% url 'mt_record' %}">
            {% csrf_token %}
            <div class="row">
              <!-- Move ID/Passport Number field and add the search button -->
                <div class="select-style-1">
                    <label for="company">Company Name</label>
                    <div class="select-position">
                    <select name="company"  required>
                        <option value="">Select Company</option>
                        <option value="western_union">Western Union</option>
                        <option value="moneygram">MoneyGram</option>
                        <option value="mpesa">M-Pesa</option>
                        <option value="dubai">Dubai</option>
                    </select>
                    </div>
                </div>
                <div class="select-style-1">
                    <label for="transaction_type">Transaction Type</label>
                    <div class="select-position">
                      <select name="transaction_type"  required>
                        <option value="">Select Transaction Type</option>
                        <option value="send">Send Money</option>
                        <option value="receive">Receive Money</option>
                      </select>
                    </div>
                </div>
                <div class="col-12">
                    <div class="input-style-1">
                        <label for="location">Location (Country)</label>
                        <input type="text" placeholder="Country" name="location" id="location" required />
                    </div>
                </div>
                <div class="col-12">
                    <div class="input-style-1">
                        <label for="sender_name">Client Name</label>
                        <input type="text" placeholder="Full Name" name="sender_name" id="sender_name" required />
                    </div>
                </div>
                <div class="col-12">
                    <div class="input-style-1">
                        <label for="sender_id_passport">Client ID/Passport</label>
                        <input type="text" placeholder="Client ID/Passport" name="sender_id_passport" id="sender_id_passport" required />
                    </div>
                </div>


            
                <div class="col-12">
                    <div class="input-style-1">
                    <label for="amount">Amount</label>
                    <input type="number" placeholder="Amount" name="amount" id="amount" required />
                    </div>
                </div>              
                <div class="col-12">
                    <button type="submit" class="main-btn primary-btn btn-hover">
                    Register
                    </button>
                </div>
            </div>
          </form>
          
        </div>
        <!-- end card -->
      </div>
      </section>

  </div>
</main>

{% endblock content %}

transactions/templates/ui/othert.html
<!-- ui/test2.html -->
<form method="GET" action="{% url 'overview' %}">
    <label for="bank_name">Bank Name:</label>
    <select id="bank_name" name="bank_name">
        <option value="">All Banks</option>
        <option value="equity_bank">Equity Bank</option>
        <option value="bk">BK</option>
        <option value="ecobank">Ecobank</option>
    </select>

    <label for="transaction_type">Transaction Type:</label>
    <select id="transaction_type" name="transaction_type">
        <option value="">All Types</option>
        <option value="deposit">Deposit</option>
        <option value="withdrawal">Withdrawal</option>
    </select>

    <label for="start_date">Start Date:</label>
    <input type="date" id="start_date" name="start_date">

    <label for="end_date">End Date:</label>
    <input type="date" id="end_date" name="end_date">

    <button type="submit">Apply Filters</button>
</form>

{% for transaction in transactions %}
    <!-- Display transaction details as needed -->
    {{ transaction.bank_name }} - {{ transaction.transaction_type }} - {{ transaction.client_name }} - {{ transaction.amount }} - {{ transaction.date }}
{% endfor %}

transactions/templates/ui/record.html
{% extends "base.html" %}

{% load static %}
{% block content %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Transaction</title>
</head>
<body>
    <h2>Create a New Transaction</h2>
    <form method="post" action="{% url 'bank_record' %}">
        {% csrf_token %}
        <label for="bank_name">Bank Name:</label>
        <input type="text" id="bank_name" name="bank_name" required>

        <label for="transaction_type">Transaction Type:</label>
        <select id="transaction_type" name="transaction_type" required>
            <option value="deposit">Deposit</option>
            <option value="withdrawal">Withdrawal</option>
        </select>

        <label for="client_name">Client Name:</label>
        <input type="text" id="client_name" name="client_name" required>

        <label for="client_id_passport">Client ID/Passport:</label>
        <input type="text" id="client_id_passport" name="client_id_passport" required>

        <label for="amount">Amount:</label>
        <input type="number" id="amount" name="amount" required>

        <button type="submit">Submit</button>
    </form>
</body>
</html>
{% endblock content %}

transactions/templates/ui/test.html
<h1>hello</h1>